// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BusinessService is the Wails boundary for the canonical A3T business API.
 * Credentials and HTTP behavior stay in Go rather than the webview.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyReviewedImport(businessID: string, reviewID: string): $CancellablePromise<$models.ImportReport | null> {
    return $Call.ByID(2416452425, businessID, reviewID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Configure(config: $models.BusinessServiceConfig): $CancellablePromise<$models.BusinessServiceStatus | null> {
    return $Call.ByID(1852369505, config).then(($result: any) => {
        return $$createType3($result);
    });
}

export function CreateBusiness(input: $models.CreateBusinessInput, operationID: string): $CancellablePromise<$models.Business | null> {
    return $Call.ByID(4058811361, input, operationID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function CreateRecord(businessID: string, input: $models.CreateRecordInput, operationID: string): $CancellablePromise<$models.RecordView | null> {
    return $Call.ByID(1134460382, businessID, input, operationID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function FindPath(businessID: string, fromRecordID: string, toRecordID: string, maxDepth: number, kinds: string[]): $CancellablePromise<$models.PathResult | null> {
    return $Call.ByID(1032140451, businessID, fromRecordID, toRecordID, maxDepth, kinds).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetBusiness(businessID: string): $CancellablePromise<$models.Business | null> {
    return $Call.ByID(332566871, businessID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetRecord(businessID: string, recordID: string): $CancellablePromise<$models.RecordView | null> {
    return $Call.ByID(3074468760, businessID, recordID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetRecordsByIDs(businessID: string, recordIDs: string[]): $CancellablePromise<$models.RecordView[]> {
    return $Call.ByID(2506801370, businessID, recordIDs).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetRevision(businessID: string, recordID: string, revisionID: string): $CancellablePromise<$models.RecordView | null> {
    return $Call.ByID(589493916, businessID, recordID, revisionID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListBusinesses(): $CancellablePromise<$models.Business[]> {
    return $Call.ByID(2889376141).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListIdentifiers(businessID: string): $CancellablePromise<$models.BusinessIdentifier[]> {
    return $Call.ByID(940081885, businessID).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ListRecordPage(businessID: string, search: string, typeCode: string, status: string, cursor: string, limit: number): $CancellablePromise<$models.RecordPage | null> {
    return $Call.ByID(465441125, businessID, search, typeCode, status, cursor, limit).then(($result: any) => {
        return $$createType15($result);
    });
}

export function ListRecords(businessID: string, search: string, typeCode: string, status: string): $CancellablePromise<$models.RecordView[]> {
    return $Call.ByID(1918671031, businessID, search, typeCode, status).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListRevisionPage(businessID: string, recordID: string, cursor: string, limit: number): $CancellablePromise<$models.RevisionPage | null> {
    return $Call.ByID(2428211533, businessID, recordID, cursor, limit).then(($result: any) => {
        return $$createType17($result);
    });
}

export function ListRevisions(businessID: string, recordID: string): $CancellablePromise<$models.RecordRevision[]> {
    return $Call.ByID(2761572783, businessID, recordID).then(($result: any) => {
        return $$createType19($result);
    });
}

export function Neighborhood(businessID: string, recordID: string, depth: number, limit: number, kinds: string[]): $CancellablePromise<$models.Neighborhood | null> {
    return $Call.ByID(1658644895, businessID, recordID, depth, limit, kinds).then(($result: any) => {
        return $$createType21($result);
    });
}

export function ProjectionStatus(businessID: string): $CancellablePromise<$models.ProjectionStatus | null> {
    return $Call.ByID(3790349188, businessID).then(($result: any) => {
        return $$createType23($result);
    });
}

export function ReviewImportSource(businessID: string, inputPath: string): $CancellablePromise<$models.ImportReviewResult | null> {
    return $Call.ByID(3653669211, businessID, inputPath).then(($result: any) => {
        return $$createType25($result);
    });
}

export function ReviseRecord(businessID: string, recordID: string, expectedVersion: number, input: $models.ReviseRecordInput): $CancellablePromise<$models.RecordView | null> {
    return $Call.ByID(3469152750, businessID, recordID, expectedVersion, input).then(($result: any) => {
        return $$createType7($result);
    });
}

export function Status(): $CancellablePromise<$models.BusinessServiceStatus | null> {
    return $Call.ByID(3926355161).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpdateBusiness(businessID: string, expectedVersion: number, input: $models.UpdateBusinessInput): $CancellablePromise<$models.Business | null> {
    return $Call.ByID(65276220, businessID, expectedVersion, input).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ImportReport.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.BusinessServiceStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.Business.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.RecordView.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.PathResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType6);
const $$createType11 = $Create.Array($$createType4);
const $$createType12 = $models.BusinessIdentifier.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.RecordPage.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.RevisionPage.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.RecordRevision.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.Neighborhood.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = $models.ProjectionStatus.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = $models.ImportReviewResult.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
