// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Business {
    "id": string;
    "tenant_id": string;
    "organization_id"?: string | null;
    "slug": string;
    "display_name": string;
    "legal_name"?: string;
    "description"?: string;
    "status": string;
    "visibility": string;
    "ontology_version"?: string;
    "version": number;
    "created_by": string;
    "updated_by": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Business instance. */
    constructor($$source: Partial<Business> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("tenant_id" in $$source)) {
            this["tenant_id"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("visibility" in $$source)) {
            this["visibility"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("created_by" in $$source)) {
            this["created_by"] = "";
        }
        if (!("updated_by" in $$source)) {
            this["updated_by"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Business instance from a string or object.
     */
    static createFrom($$source: any = {}): Business {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Business($$parsedSource as Partial<Business>);
    }
}

export class BusinessIdentifier {
    "id": string;
    "business_id": string;
    "scheme": string;
    "value": string;
    "normalized_value": string;
    "primary": boolean;
    "version": number;
    "verified_at"?: string | null;
    "metadata_json"?: string;
    "created_by": string;
    "created_at": string;

    /** Creates a new BusinessIdentifier instance. */
    constructor($$source: Partial<BusinessIdentifier> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("business_id" in $$source)) {
            this["business_id"] = "";
        }
        if (!("scheme" in $$source)) {
            this["scheme"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("normalized_value" in $$source)) {
            this["normalized_value"] = "";
        }
        if (!("primary" in $$source)) {
            this["primary"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("created_by" in $$source)) {
            this["created_by"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BusinessIdentifier instance from a string or object.
     */
    static createFrom($$source: any = {}): BusinessIdentifier {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BusinessIdentifier($$parsedSource as Partial<BusinessIdentifier>);
    }
}

export class BusinessRecord {
    "id": string;
    "business_id": string;
    "key": string;
    "type_code": string;
    "current_revision_id"?: string | null;
    "current_revision": number;
    "version": number;
    "created_by": string;
    "updated_by": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new BusinessRecord instance. */
    constructor($$source: Partial<BusinessRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("business_id" in $$source)) {
            this["business_id"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type_code" in $$source)) {
            this["type_code"] = "";
        }
        if (!("current_revision" in $$source)) {
            this["current_revision"] = 0;
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("created_by" in $$source)) {
            this["created_by"] = "";
        }
        if (!("updated_by" in $$source)) {
            this["updated_by"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BusinessRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): BusinessRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BusinessRecord($$parsedSource as Partial<BusinessRecord>);
    }
}

export class BusinessServiceConfig {
    "base_url": string;
    "access_token": string;
    "tenant_id": string;
    "actor_id": string;
    "preserve_credentials": boolean;

    /** Creates a new BusinessServiceConfig instance. */
    constructor($$source: Partial<BusinessServiceConfig> = {}) {
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("access_token" in $$source)) {
            this["access_token"] = "";
        }
        if (!("tenant_id" in $$source)) {
            this["tenant_id"] = "";
        }
        if (!("actor_id" in $$source)) {
            this["actor_id"] = "";
        }
        if (!("preserve_credentials" in $$source)) {
            this["preserve_credentials"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BusinessServiceConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BusinessServiceConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BusinessServiceConfig($$parsedSource as Partial<BusinessServiceConfig>);
    }
}

export class BusinessServiceStatus {
    "base_url": string;
    "connected": boolean;
    "ready": boolean;
    "auth_mode": string;
    "has_access_token": boolean;
    "has_development_identity": boolean;
    "message": string;

    /** Creates a new BusinessServiceStatus instance. */
    constructor($$source: Partial<BusinessServiceStatus> = {}) {
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("auth_mode" in $$source)) {
            this["auth_mode"] = "";
        }
        if (!("has_access_token" in $$source)) {
            this["has_access_token"] = false;
        }
        if (!("has_development_identity" in $$source)) {
            this["has_development_identity"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BusinessServiceStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): BusinessServiceStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BusinessServiceStatus($$parsedSource as Partial<BusinessServiceStatus>);
    }
}

export class CreateBusinessInput {
    "slug": string;
    "display_name": string;
    "legal_name"?: string;
    "description"?: string;
    "status"?: string;
    "visibility"?: string;
    "ontology_version"?: string;
    "organization_id"?: string | null;

    /** Creates a new CreateBusinessInput instance. */
    constructor($$source: Partial<CreateBusinessInput> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateBusinessInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateBusinessInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateBusinessInput($$parsedSource as Partial<CreateBusinessInput>);
    }
}

export class CreateRecordInput {
    "key": string;
    "type_code": string;
    "revision": RevisionInput;

    /** Creates a new CreateRecordInput instance. */
    constructor($$source: Partial<CreateRecordInput> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type_code" in $$source)) {
            this["type_code"] = "";
        }
        if (!("revision" in $$source)) {
            this["revision"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateRecordInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateRecordInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateRecordInput($$parsedSource as Partial<CreateRecordInput>);
    }
}

export class GraphEdge {
    "id": string;
    "source_id": string;
    "target_id"?: string | null;
    "target_ref"?: string;
    "kind": string;
    "strength"?: string;

    /** Creates a new GraphEdge instance. */
    constructor($$source: Partial<GraphEdge> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphEdge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphEdge($$parsedSource as Partial<GraphEdge>);
    }
}

export class GraphNode {
    "id": string;
    "key": string;
    "type_code": string;
    "title": string;
    "status"?: string;
    "visibility"?: string;
    "version": number;

    /** Creates a new GraphNode instance. */
    constructor($$source: Partial<GraphNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type_code" in $$source)) {
            this["type_code"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphNode instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphNode($$parsedSource as Partial<GraphNode>);
    }
}

export class ImportDiagnostic {
    "path"?: string;
    "severity": string;
    "code": string;
    "message": string;

    /** Creates a new ImportDiagnostic instance. */
    constructor($$source: Partial<ImportDiagnostic> = {}) {
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportDiagnostic instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportDiagnostic {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportDiagnostic($$parsedSource as Partial<ImportDiagnostic>);
    }
}

export class ImportReport {
    "id": string;
    "business_id": string;
    "source_name": string;
    "source_hash": string;
    "created_records": number;
    "revised_records": number;
    "unchanged_records": number;
    "resolved_relationships": number;
    "unresolved_references": number;
    "diagnostics"?: ImportDiagnostic[];
    "dry_run": boolean;
    "created_by": string;
    "created_at": string;

    /** Creates a new ImportReport instance. */
    constructor($$source: Partial<ImportReport> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("business_id" in $$source)) {
            this["business_id"] = "";
        }
        if (!("source_name" in $$source)) {
            this["source_name"] = "";
        }
        if (!("source_hash" in $$source)) {
            this["source_hash"] = "";
        }
        if (!("created_records" in $$source)) {
            this["created_records"] = 0;
        }
        if (!("revised_records" in $$source)) {
            this["revised_records"] = 0;
        }
        if (!("unchanged_records" in $$source)) {
            this["unchanged_records"] = 0;
        }
        if (!("resolved_relationships" in $$source)) {
            this["resolved_relationships"] = 0;
        }
        if (!("unresolved_references" in $$source)) {
            this["unresolved_references"] = 0;
        }
        if (!("dry_run" in $$source)) {
            this["dry_run"] = false;
        }
        if (!("created_by" in $$source)) {
            this["created_by"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportReport instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportReport {
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField9_0($$parsedSource["diagnostics"]);
        }
        return new ImportReport($$parsedSource as Partial<ImportReport>);
    }
}

export class ImportReviewResult {
    "review_id": string;
    "report": ImportReport;

    /** Creates a new ImportReviewResult instance. */
    constructor($$source: Partial<ImportReviewResult> = {}) {
        if (!("review_id" in $$source)) {
            this["review_id"] = "";
        }
        if (!("report" in $$source)) {
            this["report"] = (new ImportReport());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportReviewResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportReviewResult {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("report" in $$parsedSource) {
            $$parsedSource["report"] = $$createField1_0($$parsedSource["report"]);
        }
        return new ImportReviewResult($$parsedSource as Partial<ImportReviewResult>);
    }
}

export class Neighborhood {
    "business_id": string;
    "root_record_id": string;
    "depth": number;
    "nodes": GraphNode[];
    "edges": GraphEdge[];
    "projected_through"?: string;
    "truncated": boolean;

    /** Creates a new Neighborhood instance. */
    constructor($$source: Partial<Neighborhood> = {}) {
        if (!("business_id" in $$source)) {
            this["business_id"] = "";
        }
        if (!("root_record_id" in $$source)) {
            this["root_record_id"] = "";
        }
        if (!("depth" in $$source)) {
            this["depth"] = 0;
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Neighborhood instance from a string or object.
     */
    static createFrom($$source: any = {}): Neighborhood {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField3_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField4_0($$parsedSource["edges"]);
        }
        return new Neighborhood($$parsedSource as Partial<Neighborhood>);
    }
}

export class PathResult {
    "business_id": string;
    "from": string;
    "to": string;
    "nodes": GraphNode[];
    "edges": GraphEdge[];
    "found": boolean;

    /** Creates a new PathResult instance. */
    constructor($$source: Partial<PathResult> = {}) {
        if (!("business_id" in $$source)) {
            this["business_id"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PathResult {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField3_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField4_0($$parsedSource["edges"]);
        }
        return new PathResult($$parsedSource as Partial<PathResult>);
    }
}

export class ProjectionStatus {
    "business_id": string;
    "pending_events": number;
    "status": string;

    /** Creates a new ProjectionStatus instance. */
    constructor($$source: Partial<ProjectionStatus> = {}) {
        if (!("business_id" in $$source)) {
            this["business_id"] = "";
        }
        if (!("pending_events" in $$source)) {
            this["pending_events"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectionStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectionStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectionStatus($$parsedSource as Partial<ProjectionStatus>);
    }
}

export class RecordPage {
    "items": RecordView[];
    "next_cursor"?: string;

    /** Creates a new RecordPage instance. */
    constructor($$source: Partial<RecordPage> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordPage instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordPage {
        const $$createField0_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new RecordPage($$parsedSource as Partial<RecordPage>);
    }
}

export class RecordRelationship {
    "id": string;
    "revision_id": string;
    "source_record_id": string;
    "target_record_id"?: string | null;
    "target_key": string;
    "kind": string;
    "resolution": string;
    "strength"?: string;
    "provenance_json"?: string;
    "created_at": string;

    /** Creates a new RecordRelationship instance. */
    constructor($$source: Partial<RecordRelationship> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("revision_id" in $$source)) {
            this["revision_id"] = "";
        }
        if (!("source_record_id" in $$source)) {
            this["source_record_id"] = "";
        }
        if (!("target_key" in $$source)) {
            this["target_key"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("resolution" in $$source)) {
            this["resolution"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordRelationship instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordRelationship {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordRelationship($$parsedSource as Partial<RecordRelationship>);
    }
}

export class RecordRevision {
    "id": string;
    "record_id": string;
    "business_id": string;
    "revision": number;
    "record_version": number;
    "type_code": string;
    "title": string;
    "status"?: string;
    "domain"?: string;
    "visibility"?: string;
    "owner_ref"?: string;
    "schema_version"?: string;
    "source_version"?: string;
    "data_json": string;
    "narrative_markdown"?: string;
    "raw_markdown"?: string;
    "source_hash"?: string;
    "content_hash": string;
    "graph_hash": string;
    "source_uri"?: string;
    "source_media_type"?: string;
    "effective_at"?: string | null;
    "created_by": string;
    "created_at": string;

    /** Creates a new RecordRevision instance. */
    constructor($$source: Partial<RecordRevision> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("record_id" in $$source)) {
            this["record_id"] = "";
        }
        if (!("business_id" in $$source)) {
            this["business_id"] = "";
        }
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }
        if (!("record_version" in $$source)) {
            this["record_version"] = 0;
        }
        if (!("type_code" in $$source)) {
            this["type_code"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("data_json" in $$source)) {
            this["data_json"] = "";
        }
        if (!("content_hash" in $$source)) {
            this["content_hash"] = "";
        }
        if (!("graph_hash" in $$source)) {
            this["graph_hash"] = "";
        }
        if (!("created_by" in $$source)) {
            this["created_by"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordRevision instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordRevision {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordRevision($$parsedSource as Partial<RecordRevision>);
    }
}

export class RecordView {
    "record": BusinessRecord;
    "revision": RecordRevision;
    "relationships": RecordRelationship[];

    /** Creates a new RecordView instance. */
    constructor($$source: Partial<RecordView> = {}) {
        if (!("record" in $$source)) {
            this["record"] = (new BusinessRecord());
        }
        if (!("revision" in $$source)) {
            this["revision"] = (new RecordRevision());
        }
        if (!("relationships" in $$source)) {
            this["relationships"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordView instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordView {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("record" in $$parsedSource) {
            $$parsedSource["record"] = $$createField0_0($$parsedSource["record"]);
        }
        if ("revision" in $$parsedSource) {
            $$parsedSource["revision"] = $$createField1_0($$parsedSource["revision"]);
        }
        if ("relationships" in $$parsedSource) {
            $$parsedSource["relationships"] = $$createField2_0($$parsedSource["relationships"]);
        }
        return new RecordView($$parsedSource as Partial<RecordView>);
    }
}

export class ReviseRecordInput {
    "type_code"?: string;
    "revision": RevisionInput;

    /** Creates a new ReviseRecordInput instance. */
    constructor($$source: Partial<ReviseRecordInput> = {}) {
        if (!("revision" in $$source)) {
            this["revision"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReviseRecordInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ReviseRecordInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReviseRecordInput($$parsedSource as Partial<ReviseRecordInput>);
    }
}

export type RevisionInput = any;

export class RevisionPage {
    "items": RecordRevision[];
    "next_cursor"?: string;

    /** Creates a new RevisionPage instance. */
    constructor($$source: Partial<RevisionPage> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RevisionPage instance from a string or object.
     */
    static createFrom($$source: any = {}): RevisionPage {
        const $$createField0_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new RevisionPage($$parsedSource as Partial<RevisionPage>);
    }
}

export class UpdateBusinessInput {
    "display_name"?: string | null;
    "legal_name"?: string | null;
    "description"?: string | null;
    "status"?: string | null;
    "visibility"?: string | null;
    "ontology_version"?: string | null;

    /** Creates a new UpdateBusinessInput instance. */
    constructor($$source: Partial<UpdateBusinessInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateBusinessInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateBusinessInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateBusinessInput($$parsedSource as Partial<UpdateBusinessInput>);
    }
}

// Private type creation functions
const $$createType0 = ImportDiagnostic.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ImportReport.createFrom;
const $$createType3 = GraphNode.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = GraphEdge.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = RecordView.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = BusinessRecord.createFrom;
const $$createType10 = RecordRevision.createFrom;
const $$createType11 = RecordRelationship.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Array($$createType10);
