/**
 * BSpec Constants and Enums
 *
 * GENERATED CODE - DO NOT EDIT MANUALLY
 * Generated from BSpec v1.0.0 specification
 * Generated at: 2025-09-30T00:20:03.216238
 */

// Document type codes
export const DOCUMENT_TYPES = {
  PRD: 'PRD' as const,
  QUA: 'QUA' as const,
  ROD: 'ROD' as const,
  UXD: 'UXD' as const,
  REQ: 'REQ' as const,
  SUP: 'SUP' as const,
  FEA: 'FEA' as const,
  SVC: 'SVC' as const,
  INT: 'INT' as const,
  PSP: 'PSP' as const,
  SYS: 'SYS' as const,
  DEV: 'DEV' as const,
  DAT: 'DAT' as const,
  ANA: 'ANA' as const,
  SEC: 'SEC' as const,
  ARC: 'ARC' as const,
  INF: 'INF' as const,
  API: 'API' as const,
  PRI: 'PRI' as const,
  VST: 'VST' as const,
  KRS: 'KRS' as const,
  KPT: 'KPT' as const,
  REV: 'REV' as const,
  CST: 'CST' as const,
  CUS: 'CUS' as const,
  CHN: 'CHN' as const,
  KAC: 'KAC' as const,
  LEA: 'LEA' as const,
  ADT: 'ADT' as const,
  EXP: 'EXP' as const,
  INN: 'INN' as const,
  RND: 'RND' as const,
  FUT: 'FUT' as const,
  IGN: 'IGN' as const,
  PAI: 'PAI' as const,
  BEH: 'BEH' as const,
  CJM: 'CJM' as const,
  PER: 'PER' as const,
  CIN: 'CIN' as const,
  STO: 'STO' as const,
  EMP: 'EMP' as const,
  GAI: 'GAI' as const,
  FEE: 'FEE' as const,
  USE: 'USE' as const,
  SUR: 'SUR' as const,
  JTB: 'JTB' as const,
  LRN: 'LRN' as const,
  DEC: 'DEC' as const,
  WIS: 'WIS' as const,
  HYP: 'HYP' as const,
  RET: 'RET' as const,
  KNO: 'KNO' as const,
  MSN: 'MSN' as const,
  OBJ: 'OBJ' as const,
  STR: 'STR' as const,
  VSN: 'VSN' as const,
  PUR: 'PUR' as const,
  VAL: 'VAL' as const,
  MOT: 'MOT' as const,
  THY: 'THY' as const,
  CTL: 'CTL' as const,
  LEG: 'LEG' as const,
  GOV: 'GOV' as const,
  COM: 'COM' as const,
  INC: 'INC' as const,
  INS: 'INS' as const,
  RSK: 'RSK' as const,
  ETH: 'ETH' as const,
  OPP: 'OPP' as const,
  ECO: 'ECO' as const,
  SEG: 'SEG' as const,
  MKT: 'MKT' as const,
  POS: 'POS' as const,
  REG: 'REG' as const,
  MAC: 'MAC' as const,
  THR: 'THR' as const,
  CMP: 'CMP' as const,
  TRN: 'TRN' as const,
  TON: 'TON' as const,
  VID: 'VID' as const,
  BRD: 'BRD' as const,
  CAM: 'CAM' as const,
  CNT: 'CNT' as const,
  PRF: 'PRF' as const,
  MSG: 'MSG' as const,
  IFL: 'IFL' as const,
  MCH: 'MCH' as const,
  SEO: 'SEO' as const,
  SOC: 'SOC' as const,
  BPO: 'BPO' as const,
  REP: 'REP' as const,
  FOR: 'FOR' as const,
  TAX: 'TAX' as const,
  FIN: 'FIN' as const,
  FND: 'FND' as const,
  INV: 'INV' as const,
  AUD: 'AUD' as const,
  MET: 'MET' as const,
  BUD: 'BUD' as const,
  VLU: 'VLU' as const,
  POL: 'POL' as const,
  SKI: 'SKI' as const,
  VND: 'VND' as const,
  PRO: 'PRO' as const,
  CAP: 'CAP' as const,
  WFL: 'WFL' as const,
  FAC: 'FAC' as const,
  SLA: 'SLA' as const,
  ROL: 'ROL' as const,
  OPS: 'OPS' as const,
  ORG: 'ORG' as const,
  TEA: 'TEA' as const,
  ACQ: 'ACQ' as const,
  ACT: 'ACT' as const,
  BMC: 'BMC' as const,
  CAC: 'CAC' as const,
  CRI: 'CRI' as const,
  GRW: 'GRW' as const,
  GTM: 'GTM' as const,
  GVN: 'GVN' as const,
  LTV: 'LTV' as const,
  MIT: 'MIT' as const,
  PRC: 'PRC' as const,
  PRT: 'PRT' as const,
  REL: 'REL' as const,
  RES: 'RES' as const,
  SCL: 'SCL' as const,
  STA: 'STA' as const,
  TOO: 'TOO' as const,
  UNT: 'UNT' as const,
} as const;

// Domain names (simplified for build compatibility)
export const DOMAINS = {
  PRODUCT_AND_SERVICE: 'Product & Service' as const,
  TECHNOLOGY_AND_DATA: 'Technology & Data' as const,
  BUSINESS_MODEL: 'Business Model' as const,
  GROWTH_AND_INNOVATION: 'Growth & Innovation' as const,
  CUSTOMER_AND_VALUE: 'Customer & Value' as const,
  LEARNING_AND_DECISIONS: 'Learning & Decisions' as const,
  STRATEGIC_FOUNDATION: 'Strategic Foundation' as const,
  RISK_AND_GOVERNANCE: 'Risk & Governance' as const,
  MARKET_AND_ENVIRONMENT: 'Market & Environment' as const,
  BRAND_AND_MARKETING: 'Brand & Marketing' as const,
  FINANCIAL_AND_INVESTMENT: 'Financial & Investment' as const,
  OPERATIONS_AND_EXECUTION: 'Operations & Execution' as const,
} as const;

// Conformance levels
export const CONFORMANCE_LEVELS = {
  BRONZE: 'bronze' as const,
  SILVER: 'silver' as const,
  GOLD: 'gold' as const,
} as const;

// Export version
export const VERSION = '1.0.0';